name: flutter_youtube_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  better_player_plus: ^1.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/yt_logo_dark.png
